spring:
  application:
    name: agro-manager
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8080

app:
  mail:
    from-name: ${MAIL_FROM_NAME:Agro Manager}
    from-address: ${MAIL_FROM_ADDRESS:john.doe@email.com}