-- V2: Accounts table — the root tenant entity. Every other business entity
-- (users, crops, transactions, etc.) will reference this table via account_id.

CREATE TABLE accounts (
                          id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name       VARCHAR(120) NOT NULL,
                          status     VARCHAR(20)  NOT NULL,
                          created_at TIMESTAMP    NOT NULL,
                          updated_at TIMESTAMP    NOT NULL,
                          version    BIGINT       NOT NULL,
                          CONSTRAINT ck_accounts_status CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);