-- V3: Users table.
--
-- Every user belongs to exactly one account (ManyToOne). Authentication can
-- be either local (password hash) or federated (Google OIDC subject); a
-- CHECK constraint enforces that at least one credential is present.
--
-- Email is globally unique. Roles are stored as strings for forward
-- compatibility (adding a role doesn't require an ALTER TABLE).

CREATE TABLE users (
                       id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       account_id      BIGINT       NOT NULL,
                       email           VARCHAR(255) NOT NULL,
                       name            VARCHAR(120) NOT NULL,
                       password_hash   VARCHAR(255),
                       google_subject  VARCHAR(255),
                       role            VARCHAR(20)  NOT NULL,
                       status          VARCHAR(20)  NOT NULL,
                       created_at      TIMESTAMP    NOT NULL,
                       updated_at      TIMESTAMP    NOT NULL,
                       version         BIGINT       NOT NULL,

                       CONSTRAINT fk_users_account       FOREIGN KEY (account_id) REFERENCES accounts(id),
                       CONSTRAINT uk_users_email         UNIQUE (email),
                       CONSTRAINT uk_users_google        UNIQUE (google_subject),
                       CONSTRAINT ck_users_role          CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER')),
                       CONSTRAINT ck_users_status        CHECK (status IN ('ACTIVE', 'INACTIVE')),
                       CONSTRAINT ck_users_credentials   CHECK (password_hash IS NOT NULL OR google_subject IS NOT NULL)
);

CREATE INDEX ix_users_account ON users(account_id);