package br.com.hadryan.agro.manager.shared.domain;

import jakarta.persistence.*;
import lombok.Getter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.Objects;

/**
 * Base class for all JPA entities.
 *
 * <p>Provides:
 * <ul>
 *   <li>A synthetic {@code Long} primary key generated by the database.</li>
 *   <li>{@code createdAt} / {@code updatedAt} audit timestamps, maintained
 *       automatically by Spring Data JPA auditing.</li>
 *   <li>{@code version} field for optimistic locking — concurrent updates
 *       to the same row will fail fast instead of silently overwriting.</li>
 *   <li>Equality based on the primary key (two persisted entities with the
 *       same id are equal; transient entities are only equal to themselves).</li>
 * </ul>
 *
 * <p>Subclasses must be annotated with {@code @Entity} and will inherit all
 * the fields above.
 */
@Getter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Version
    @Column(nullable = false)
    private Long version;

    /**
     * Equality is based on the persisted id. Two entities without an id
     * (transient) are only equal to themselves by reference, which avoids
     * subtle bugs when putting unsaved entities into hash-based collections.
     */
    @Override
    public final boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof BaseEntity that)) {
            return false;
        }
        return id != null && Objects.equals(id, that.id);
    }

    /**
     * Constant hash code. Using the id here would break contracts the moment
     * JPA assigns an id on flush (the hash would change while the entity sits
     * in a HashSet). A constant hash is the standard workaround for JPA
     * entities and is acceptable because collections of entities are usually
     * small.
     */
    @Override
    public final int hashCode() {
        return getClass().hashCode();
    }
}
